site_name: Le Petit Roque de Sèvres Ville-d'Avray
site_url: https://lfaber91.github.io/site_sva
nav:
  - Accueil: accueil.md
  - Inscription: inscription.md
  - Horaires: horaires.md
  - Blog: index.md
  - A Propos: about.md
theme:
    name: simplex
    custom_dir: custom_theme/

extra_css:
  - css/style.css

plugins:
  - search
  - mermaid2:
      version: 10.0.2
      arguments:
        securityLevel: 'loose'
  - blogging:
      dirs:
        - blog
      features:
        tags:
          index_page: tags.md
          insert: top
      theme:
        name: button
        options:
          plain_button: false
          label: Lire