site_name: Le Petit Roque de Sèvres Ville-d'Avray
site_url: https://lfaber91.github.io/SVA

nav:
  - Accueil: accueil.md
  - Inscription: inscription.md
  - Horaires & Cours:
    - Horaires: horaires.md
    - Cours: cours.md
  - Effectifs: effectifs.md
  - Contact:
    - Contactez nous: contact.md
    - Administratif: administratif.md
  - Divers:
      - Problèmes: problemes.md
      - Ressources Pédagogiques: ressources_pedagogiques_ffe.md
      - Lectures: lectures.md
      - Films: films.md
      - Histoire du club: histoire.md
      - Liens: liens.md
  - Blog: index.md

theme:
    name: simplex
    custom_dir: custom_theme/

validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn
extra_css:
  - css/style.css

plugins:
  - search
  - mermaid2:
      version: 10.0.2
      arguments:
        securityLevel: 'loose'
  - blogging:
      dirs:
        - blog
      features:
        tags:
          index_page: tags.md
          insert: top
      theme:
        name: button
        options:
          plain_button: false
          label: Lire

markdown_extensions:
  - toc:
      permalink: true